name: main

on:
  push:
    branches: [ default ]
  pull_request:
    branches: [ default ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        buildType: [ Release, Debug ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Prepare
        run: |
          ls
          mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.buildType}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.buildType}}

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            ${{github.workspace}}/build/dxFeedCppSample.*
            ${{github.workspace}}/build/*.so
            ${{github.workspace}}/build/*.dylib
            ${{github.workspace}}/build/*.dll